# file: code/.github/workflows/server-ci.yml

name: Server CI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'server/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    defaults:
      run:
        working-directory: ./server
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - name: Install dependencies
      run: npm ci

    - name: Run linter
      # run: npm run lint # <<<<<<< VÔ HIỆU HÓA NÓ Ở ĐÂY

    # - name: Run tests
    #   run: npm test