
# file: code/render.yaml

services:
  # === Dịch vụ Backend (Bộ Não) ===
  - name: myriad-scrolls-api
    type: web          # Loại dịch vụ là web server
    env: docker        # <-- TUYỆT CHIÊU LÀ ĐÂY! BẮT BUỘC NÓ DÙNG DOCKER
    rootDir: ./server  # Chỉ cho nó vào đúng thư mục server
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: myriad-scrolls-db # Tên database mình sẽ tạo trên Render
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Để Render tự tạo một chuỗi bí mật an toàn
      - key: JWT_ACCESS_TOKEN_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 8000
      - key: CORS_ORIGIN
        fromService: # Tự động lấy link của frontend
          type: static
          name: myriad-scrolls-client
          property: url

  # === Dịch vụ Frontend (Giao Diện) ===
  - name: myriad-scrolls-client
    type: static       # Loại dịch vụ là trang web tĩnh
    rootDir: ./client  # Chỉ cho nó vào đúng thư mục client
    buildCommand: npm run build
    publishDir: ./dist # Thư mục chứa kết quả sau khi build
    envVars:
      - key: VITE_API_BASE_URL
        fromService: # Tự động lấy link của backend
          type: web
          name: myriad-scrolls-api
          property: url

  # === Dịch vụ Database (Trái Tim) ===
  - name: myriad-scrolls-db
    type: pserv        # Loại dịch vụ là database PostgreSQL (Free Tier)
    # Render không có Mongo, mình dùng tạm Postgres miễn phí để test
    # Hoặc ông có thể xóa khối này và vẫn dùng link Mongo Atlas ở trên
    # Nếu dùng Mongo Atlas, thì sửa lại khối envVars của backend